defaults: &defaults
  docker:
    - image: circleci/node:latest-browsers
  working_directory: ~/repo

version: 2
jobs:
  build_frontend:
    docker:
      - image: circleci/node:11.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: lint:css
          command: npm run lint:css
      - run:
          name: lint:js
          command: npm run lint:js
      - run:
          name: Build frontend
          command: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build_docker:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t 12evgen/pokemon:latest .
      - deploy:
          name: Push Pokemon to DockerHub
          command: |
            PACKAGE_VERSION=$(node -p "require('./package.json').version")
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker tag 12evgen/pokemon:latest 12evgen/pokemon:$PACKAGE_VERSION
            docker push 12evgen/pokemon:latest
            docker push 12evgen/pokemon:$PACKAGE_VERSION

  deploy-to-staging:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundles-{{ .Revision }}
      - run:
          name: Login registry.heroku.com
          command: docker login --username=${HEROKU_LOGIN} --password=${HEROKU_API_KEY} registry.heroku.com
      - run:
          name: Pull docker image from Docker Hub
          command: |
            docker pull 12evgen/pokemon:latest
      - run:
          name: Tag image for Heroku DTR
          command: |
            docker tag 12evgen/pokemon:latest registry.heroku.com/${HEROKU_APP_NAME_STAGE}/web
      - run:
          name: Push image to Heroku
          command: |
            docker push registry.heroku.com/${HEROKU_APP_NAME_STAGE}/web
      - run:
          name: Release new container
          command: |
            heroku container:release web --app HEROKU_APP_NAME_STAGE

  deploy-to-production:
    docker:
      - image: 12evgen/pokemon:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundles-{{ .Revision }}
      - add_ssh_keys:
          fngerprints:
            - "c7:1f:fb:eb:c0:79:6b:c9:f7:71:62:d6:f5:c0:d5:e7"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  release:
    jobs:
      - build_frontend:
          filters:
            branches:
              only: master
      - build_docker:
          filters:
            branches:
              only: master
      - hold-deploy-prod:
          type: approval
          requires:
            - build_frontend
          filters:
            branches:
              only: master
      - deploy-to-production:
          requires:
            - hold-deploy-prod
            - build_frontend
          filters:
            branches:
              only: master

  development:
    jobs:
      - build_frontend:
          filters:
            branches:
              ignore: master
      - build_docker:
          requires:
            - build_frontend
          filters:
            branches:
              ignore: master
      - hold-deploy-stage:
          type: approval
          requires:
            - build_frontend
          filters:
            branches:
              ignore: master
      - deploy-to-staging:
          requires:
            - build_docker
            - hold-deploy-stage
            - build_frontend
          filters:
             branches:
              ignore: master
